### ISSUE TITLE
出错

### ISSUE THREAD

**Issue by MisterQX** [ovear/kemono-dl#1]
您好，请问我下载的时候弹出这个提示是什么意思

D:\Program Files\Python310\lib\site-packages\bs4\__init__.py:435: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  warnings.warn(

**Comment by Ovear** [comment]
麻烦提供下运行参数和完整的错误提示。
