### ISSUE TITLE
I'm getting `Domain not in cookie files, cookie won't work properly`

### ISSUE THREAD

**Issue by Deses** [ovear/kemono-dl#12]
### Version

Version: 2022.04.28

### Your Command

```bash

python kemono-dl.py --verbose --cookies coomer.cookie --quiet --filename-pattern "{title} - {index}.{ext}" --dirname-pattern downloads/XXXXXXX --dateafter 20230801 --links https://coomer.party/XXXXXXX 

```

### Description of bug
I downloaded the cookie using [Cookie Downloader](https://chrome.google.com/webstore/detail/cookie-downloader/epldkbdhmpdcdgcolndopgkigelnmlmo), I pass the file to the command and I get that error.

`Domain not in cookie files, cookie won't work properly`

Even though I get the message, the files get downloaded fine regardless.

This is the cookie:
```
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html

.coomer.party	TRUE	/	FALSE	9999999999	__ddg1_	xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
coomer.party	FALSE	/	FALSE	9999999999	_pk_xxxxxxxxxxxxxxxxxxxxxxxxxxxx
coomer.party	FALSE	/	FALSE	9999999999	_pk_xxxxxxxxxxxxxx
```

### How To Reproduce
Just run the script normally. I'm running the script from the Linux Mint (20.3) Command Line through SSH.

### Error messages and tracebacks

No errors or tracebacks other than the one I already mentioned.

### Additional comments
I took a look at the code and the regexp in args.py line 228~231 match correctly with my cookie, so I'm not entirely sure whats happening.

**Comment by Deses** [comment]
BY THE WAY, in [README.md's line 112](https://github.com/ovear/kemono-dl/blob/634bf2f82caafe87d368fb72e6356e2760719297/README.md?plain=1#L112) you should change `--quite` to `--quiet`. 😝

**Comment by Ovear** [comment]
> Domain not in cookie files, cookie won't work properly

This is a warning message that indicates the downloader didn't load your cookie file properly in this case. 

But I could not reproduce according to the information you provided. I use the recommended `Get cookies.txt LOCALLY` extension since [Cookie Downloader](https://chrome.google.com/webstore/detail/cookie-downloader/epldkbdhmpdcdgcolndopgkigelnmlmo) required logged in Instagram to activate its function.

I would recommend to try the recommended extension to see if it fixes this.

> BY THE WAY, in [README.md's line 112](https://github.com/ovear/kemono-dl/blob/634bf2f82caafe87d368fb72e6356e2760719297/README.md?plain=1#L112) you should change --quite to --quiet. stuck_out_tongue_closed_eyes

Noted, thanks for report.

**Comment by Deses** [comment]
It worked!

I re-downloaded the cookies with `Get cookies.txt LOCALLY` and it stopped complaining.

Thank you!
