### ISSUE TITLE
kemono-dl.py: error: unrecognized arguments: https://kemono.su/fantia/user

### ISSUE THREAD

**Issue by Caxapok-X** [ovear/kemono-dl#17]
Everything worked well until one day I decided to save the photos I liked from the kemono website. I got this error, what could be the problem, I tried different combinations and nothing worked for me. I enter a simple command and get this message. (kemono-dl.py: error: unrecognized arguments: https://kemono.su/fantia/user/00000). Although a couple of months ago everything worked without problems.

python 3.10.6
windows 11
use command:     python kemono-dl.py --cookies "cookie.txt" https://kemono.su/fantia/user/00000

**Comment by Ovear** [comment]
The correct command shou be : python kemono-dl.py --cookies "cookie.txt" **--links** https://kemono.su/fantia/user/00000
